name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [22]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Run Zig Side tests
        run: zig build test

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install Pnpm
        run: npm install -g corepack@latest --force

      - name: Setup corepack
        run: corepack enable && pnpm install
      - name: Build Project
        run: zig build wasm
      - name: Run Test
        run: pnpm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
